### ISSUE TITLE
learn about Firebase

### ISSUE THREAD

**Issue by GuySuday** [TechnionYP5779/team2-Appark#4]
see https://webcourse.cs.technion.ac.il/236503/Winter2018-2019/ho/WCFiles/Firebase%20Tutorial%20-%20with%20notes.pdf

**Comment by addirabasker** [comment]
this is an ongoing task... and each time we need to search different things.
anyway the whole point of this issue was to learn how to connect our project with firebase and now all of us know how to do this so this issue can be closed.

**Comment by addirabasker** [comment]
We chose Firebase after a research we've made earlier when we decided to split to two team.
This issue was opened for learning how to use Firebase with android studio. and the results are the usage of this DB in our code.
