### ISSUE TITLE
Add a google map page where all the offers marked as pins

### ISSUE THREAD

**Issue by GuySuday** [TechnionYP5779/team2-Appark#44]
![image](https://user-images.githubusercontent.com/19148420/50284273-3b047f00-0461-11e9-8e10-37b8561d405f.png)

**Comment by talporat** [comment]
these are the relevant commits :
4bbf266332d795d95d446b354a59483d19b88a20 16d75bb99f42e40a763436db6fded5e2bb0b3a33 6ec1ef949aa6977006ac49d2715d40755db34471
