### ISSUE TITLE
Remove old offers

### ISSUE THREAD

**Issue by neryac** [TechnionYP5779/team2-Appark#64]
make sure offers which end before the current time, won't be in the available offers (maybe even delete those completely).

**Comment by neryac** [comment]
nor really deleting it, just don't show it while viewing offers

**Comment by talporat** [comment]
these are the relevant commits :
f7a52ae2543e8711cfc70968462aea6d7a81f83d a398935af55e0da253855269e6c754dff38324d2 1496df3e83cac0bcb48abc4566626157a2212052
