### ISSUE TITLE
Create a presentation for Sprint-One submission

### ISSUE THREAD

**Issue by DorKab** [TechnionYP5779/team2-Appark#88]
The presentation should include:

- [x] What we tried
- [x] What we have done
- [x] How we worked
- [x] Main features of the final product
- [x] Screenshots
- [x] etc.

**Comment by addirabasker** [comment]
Done

**Comment by GuySuday** [comment]
The presentation can be found [here](https://github.com/TechnionYP5779/team2/wiki/First-Presentation---02.01.2019)
