### ISSUE TITLE
create TimeSlot class

### ISSUE THREAD

**Issue by GuySuday** [TechnionYP5779/team2-Appark#9]
see https://github.com/TechnionYP5779/team2/blob/ConsoleDemo/src/main/java/il/org/parking/demo/SlotImplementation.java

**Comment by addirabasker** [comment]
need to check these three java classes for time managment:

- [ ] Date
- [ ] Time
- [ ] Calendar

**Comment by addirabasker** [comment]
found this article:
http://www.ntu.edu.sg/home/ehchua/programming/java/DateTimeCalendar.html
might be worth readin

**Comment by addirabasker** [comment]
so far i found out that Date/Time goes together and as the article tells it used to managed current timestamp and not the future(time-wise).
furthermore, it seems like calender should do the job.
another article : https://www.mkyong.com/java/java-date-and-calendar-examples/
![image](https://user-images.githubusercontent.com/33811361/49951694-34c34f80-ff03-11e8-9b84-cd19e282af6c.png)
this is a way we can get date-time input and save it to the system pretty easly.

**Comment by GuySuday** [comment]
I also think Calendar is the right choice

**Comment by addirabasker** [comment]
relevent commits:
e8fa5985df85fff8513badd85a258e5d3de61ed4
641f0588912b4b67f886acff6b703b2529647d08
